# airflow-sqlserver.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: airflow

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: airflow-webserver
          image: <your_airflow_image_name>
          ports:
            - containerPort: 8080
          env:
           

---

apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  selector:
    app: airflow-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
        - name: sql-server
          image: <your_sql_server_image_name>
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "Mudar@123"
            - name: ACCEPT_EULA
              value: "Y"
          volumeMounts:
            - name: sqlserver-data
              mountPath: /var/opt/mssql/data

---

apiVersion: v1
kind: Service
metadata:
  name: sql-server
  namespace: airflow
spec:
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
